name: Java CI (sin Maven ni Gradle)

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código
      uses: actions/checkout@v4

    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compilar
      run: |
        javac -d out $(find src -name "*.java")

    - name: Ejecutar programa con datos simulados
      run: |
        echo -e "Manzana\n2.5\n10\nManzana\n2.5\n10" | java -cp out Actividad_Evaluable_RA3_RA4.Principal
